import pandas as pd

# Lista completa de 100 características com suporte a letras invertidas e espelhadas
caracteristicas_100 = [
    # NUTRIÇÃO (30 itens)
    ["rs4988235", "Tolerância à Lactose", "Nutrição", "AA:Tolerante, TT:Tolerante, AG:Tolerante, CT:Tolerante, GG:Intolerante, CC:Intolerante"],
    ["rs762551", "Metabolismo de Cafeína", "Nutrição", "AA:Rápido, TT:Rápido, AC:Lento, GT:Lento, CC:Muito Lento, GG:Muito Lento"],
    ["rs9939609", "Tendência ao Ganho de Peso", "Nutrição", "TT:Baixa, AA:Baixa, AT:Média, AA:Alta, TT:Alta"],
    ["rs1801133", "Processamento de Ácido Fólico (B9)", "Nutrição", "CC:Normal, GG:Normal, CT:Reduzido, AG:Reduzido, TT:Baixo, AA:Baixo"],
    ["rs602662", "Absorção de Vitamina B12", "Nutrição", "AA:Eficiente, TT:Eficiente, AG:Normal, CT:Normal, GG:Reduzida, CC:Reduzida"],
    ["rs1544410", "Receptor de Vitamina D", "Nutrição", "AA:Alta Eficiência, TT:Alta Eficiência, AG:Normal, CT:Normal, GG:Baixa Eficiência, CC:Baixa Eficiência"],
    ["rs7501331", "Vitamina A (Betacaroteno)", "Nutrição", "CC:Eficiente, GG:Eficiente, CT:Média, AG:Média, TT:Baixa, AA:Baixa"],
    ["rs174537", "Metabolismo de Ômega-3", "Nutrição", "GG:Eficiente, CC:Eficiente, GT:Média, AC:Média, TT:Baixa, AA:Baixa"],
    ["rs35874116", "Preferência por Doces", "Nutrição", "CC:Alta, GG:Alta, CT:Média, AG:Média, TT:Baixa, AA:Baixa"],
    ["rs17608059", "Desejo por Açúcar", "Nutrição", "AA:Alto, TT:Alto, AG:Médio, CT:Médio, GG:Normal, CC:Normal"],
    ["rs13266634", "Necessidade de Zinco", "Nutrição", "CC:Baixa, GG:Baixa, CT:Média, AG:Média, TT:Alta, AA:Alta"],
    ["rs33972313", "Transporte de Vitamina C", "Nutrição", "GG:Eficiente, CC:Eficiente, AG:Médio, CT:Médio, AA:Baixo, TT:Baixo"],
    ["rs1801282", "Resposta a Gorduras Saudáveis", "Nutrição", "CC:Ótima, GG:Ótima, CG:Boa, TT:Normal, AA:Normal"],
    ["rs5400", "Sensibilidade à Glicose", "Nutrição", "GG:Alta, CC:Alta, AG:Média, CT:Média, AA:Normal, TT:Normal"],
    ["rs11083085", "Digestão de Amidos", "Nutrição", "AA:Rápida, TT:Rápida, AG:Média, CT:Média, GG:Lenta, CC:Lenta"],
    ["rs4654748", "Níveis de Vitamina B6", "Nutrição", "CC:Normais, GG:Normais, CT:Baixos, AG:Baixos, TT:Muito Baixos, AA:Muito Baixos"],
    ["rs1801198", "Transporte de B12 para Células", "Nutrição", "CC:Eficiente, GG:Eficiente, CG:Normal, TT:Reduzido, AA:Reduzido"],
    ["rs1050450", "Necessidade de Selênio", "Nutrição", "CC:Normal, GG:Normal, CT:Aumentada, AG:Aumentada, TT:Alta, AA:Alta"],
    ["rs1801394", "Reciclagem de Vitamina B12", "Nutrição", "AA:Eficiente, TT:Eficiente, AG:Normal, CT:Normal, GG:Lenta, CC:Lenta"],
    ["rs1126809", "Produção de Melanina", "Nutrição", "GG:Alta, CC:Alta, AG:Média, CT:Média, AA:Baixa, TT:Baixa"],
    ["rs174546", "Gorduras Vegetais", "Nutrição", "CC:Eficiente, GG:Eficiente, CT:Normal, AG:Normal, TT:Lento, AA:Lento"],
    ["rs11045419", "Níveis de Magnésio", "Nutrição", "CC:Normais, GG:Normais, CT:Médios, AG:Médios, TT:Baixos, AA:Baixos"],
    ["rs4644", "Resposta à Vitamina E", "Nutrição", "AA:Boa, TT:Boa, AC:Média, GT:Média, CC:Baixa, GG:Baixa"],
    ["rs641738", "Gordura no Fígado (Risco)", "Nutrição", "CC:Baixo, GG:Baixo, CT:Médio, AG:Médio, TT:Aumentado, AA:Aumentado"],
    ["rs10741657", "Ativação de Vitamina D", "Nutrição", "GG:Rápida, CC:Rápida, AG:Normal, CT:Normal, AA:Lenta, TT:Lenta"],
    ["rs2336371", "Níveis de Iodo", "Nutrição", "GG:Normais, CC:Normais, AG:Baixos, CT:Baixos, AA:Muito Baixos, TT:Muito Baixos"],
    ["rs1801274", "Resposta à Dieta Mediterrânea", "Nutrição", "CC:Excelente, GG:Excelente, CT:Boa, AG:Boa, TT:Normal, AA:Normal"],
    ["rs712", "Vitamina B12 no Sangue", "Nutrição", "GG:Altos, CC:Altos, GT:Médios, AC:Médios, TT:Baixos, AA:Baixos"],
    ["rs8066560", "Sensibilidade ao Glúten", "Nutrição", "CC:Baixa, GG:Baixa, CT:Média, AG:Média, TT:Aumentada, AA:Aumentada"],
    ["rs12272004", "Metabolismo de Vitamina B1", "Nutrição", "GG:Normal, CC:Normal, AG:Reduzido, CT:Reduzido, AA:Baixo, TT:Baixo"],

    # COMPORTAMENTO (25 itens)
    ["rs4680", "Resiliência ao Estresse", "Comportamento", "GG:Resiliente, CC:Resiliente, AG:Equilibrado, AA:Focado/Ansioso, TT:Focado/Ansioso"],
    ["rs6265", "Memória e Aprendizado", "Comportamento", "GG:Alta, CC:Alta, AG:Média, AA:Baixa, TT:Baixa"],
    ["rs53576", "Sociabilidade e Empatia", "Comportamento", "GG:Alta, CC:Alta, AG:Média, AA:Reservado, TT:Reservado"],
    ["rs1800497", "Busca por Novidades", "Comportamento", "AA:Alta, TT:Alta, AG:Média, GG:Normal, CC:Normal"],
    ["rs1799971", "Sensibilidade à Dor", "Comportamento", "AA:Alta, TT:Alta, AG:Média, GG:Baixa, CC:Baixa"],
    ["rs324420", "Ansiedade e Humor", "Comportamento", "CC:Estável, GG:Estável, AC:Misto, AA:Reativo, TT:Reativo"],
    ["rs6311", "Criatividade", "Comportamento", "CC:Alta, GG:Alta, CT:Média, TT:Normal, AA:Normal"],
    ["rs10830963", "Qualidade do Sono", "Comportamento", "GG:Boa, CC:Boa, AG:Média, AA:Irregular, TT:Irregular"],
    ["rs16969968", "Vício em Nicotina", "Comportamento", "AA:Alto Risco, TT:Alto Risco, AG:Médio, GG:Baixo, CC:Baixo"],
    ["rs17070145", "Memória de Longo Prazo", "Comportamento", "TT:Excelente, AA:Excelente, CT:Boa, CC:Normal, GG:Normal"],
    ["rs25531", "Transporte de Serotonina", "Comportamento", "AA:Eficiente, TT:Eficiente, AG:Normal, GG:Baixo, CC:Baixo"],
    ["rs6323", "Estabilidade Emocional", "Comportamento", "GG:Alta, CC:Alta, GT:Média, TT:Baixa, AA:Baixa"],
    ["rs4673", "Estresse Oxidativo no Cérebro", "Comportamento", "TT:Protegido, AA:Protegido, CT:Médio, CC:Exposto, GG:Exposto"],
    ["rs16139", "Recuperação de Traumas", "Comportamento", "CC:Rápida, GG:Rápida, CT:Média, TT:Lenta, AA:Lenta"],
    ["rs362545", "Atenção Visual", "Comportamento", "GG:Rápida, CC:Rápida, AG:Média, AA:Normal, TT:Normal"],
    ["rs767649", "Ansiedade por Cafeína", "Comportamento", "TT:Alta, AA:Alta, AC:Média, CC:Baixa, GG:Baixa"],
    ["rs10993994", "Velocidade de Raciocínio", "Comportamento", "GG:Alta, CC:Alta, AG:Média, AA:Normal, TT:Normal"],
    ["rs2020917", "Planejamento e Organização", "Comportamento", "GG:Alta, CC:Alta, AG:Média, AA:Normal, TT:Normal"],
    ["rs13210119", "Aprendizado com Erros", "Comportamento", "GG:Eficiente, CC:Eficiente, AG:Médio, AA:Lento, TT:Lento"],
    ["rs6277", "Recepção de Dopamina", "Comportamento", "CC:Alta, GG:Alta, CT:Média, TT:Baixa, AA:Baixa"],
    ["rs1076560", "Lógica e Matemática", "Comportamento", "AA:Alta, TT:Alta, AC:Média, CC:Normal, GG:Normal"],
    ["rs1800955", "Curiosidade Intelectual", "Comportamento", "CC:Alta, GG:Alta, CT:Média, TT:Normal, AA:Normal"],
    ["rs4243967", "Foco em Tarefas Repetitivas", "Comportamento", "AA:Alto, TT:Alto, AG:Médio, GG:Baixo, CC:Baixo"],
    ["rs1137101", "Paciência e Controle", "Comportamento", "GG:Alto, CC:Alto, AG:Médio, AA:Baixo, TT:Baixo"],
    ["rs22227", "Desejo por Doces", "Comportamento", "GG:Alto Risco, CC:Alto Risco, AG:Médio, AA:Normal, TT:Normal"],

    # FÍSICO E APARÊNCIA (25 itens)
    ["rs1815739", "Potência Muscular (ACTN3)", "Esporte", "CC:Força e Explosão, GG:Força e Explosão, CT:Misto, TT:Resistência, AA:Resistência"],
    ["rs12913832", "Cor dos Olhos", "Aparência", "GG:Castanhos, CC:Castanhos, AG:Castanhos/Escuros, AA:Claros, TT:Claros"],
    ["rs17822931", "Odor Corporal e Cera", "Aparência", "CC:Forte/Úmida, GG:Forte/Úmida, CT:Úmida, TT:Suave/Seca, AA:Suave/Seca"],
    ["rs1805007", "Cabelo Ruivo e Sardas", "Aparência", "TT:Ruivo, AA:Ruivo, CT:Portador, CC:Não-ruivo, GG:Não-ruivo"],
    ["rs6152", "Tendência à Calvície", "Aparência", "AA:Alta, TT:Alta, AG:Média, GG:Baixa, CC:Baixa"],
    ["rs10427255", "Espirro por Claridade", "Aparência", "TT:Sim, AA:Sim, CT:Possível, CC:Não, GG:Não"],
    ["rs16891982", "Cor Escura do Cabelo", "Aparência", "GG:Escuro, CC:Escuro, GT:Médio, TT:Claro, AA:Claro"],
    ["rs12203592", "Cabelos Brancos Precoces", "Aparência", "TT:Aumentado, AA:Aumentado, CT:Médio, CC:Normal, GG:Normal"],
    ["rs1426654", "Tom de Pele", "Aparência", "AA:Claro, TT:Claro, AG:Médio, GG:Escuro, CC:Escuro"],
    ["rs11540855", "Rugas e Envelhecimento Solar", "Aparência", "TT:Aumentado, AA:Aumentado, CT:Normal, CC:Resistente, GG:Resistente"],
    ["rs11550691", "Tendência a Estrias", "Aparência", "AA:Alta, TT:Alta, AG:Média, GG:Baixa, CC:Baixa"],
    ["rs3827760", "Espessura do Cabelo", "Aparência", "AA:Grosso, TT:Grosso, AG:Médio, GG:Fino, CC:Fino"],
    ["rs1800407", "Intensidade da Pigmentação", "Aparência", "GG:Alta, CC:Alta, AG:Média, AA:Baixa, TT:Baixa"],
    ["rs12896399", "Cabelo Loiro vs Castanho", "Aparência", "GG:Loiro, CC:Loiro, GT:Castanho Claro, TT:Castanho Escuro, AA:Castanho Escuro"],
    ["rs7559271", "Formato do Nariz", "Aparência", "CC:Larga, GG:Larga, CT:Média, TT:Estreita, AA:Estreita"],
    ["rs11235939", "Espessura das Pálpebras", "Aparência", "AA:Grossa, TT:Grossa, AG:Média, GG:Fina, CC:Fina"],
    ["rs1482852", "Densidade da Barba", "Aparência", "AA:Densa, TT:Densa, AG:Média, GG:Rala, CC:Rala"],
    ["rs198152", "Força dos Dentes", "Aparência", "AA:Forte, TT:Forte, AG:Média, GG:Frágil, CC:Frágil"],
    ["rs2606343", "Tendência a Sardas", "Aparência", "CC:Alta, GG:Alta, CT:Média, TT:Baixa, AA:Baixa"],
    ["rs12150053", "Espessura das Sobrancelhas", "Aparência", "TT:Grossas, AA:Grossas, CT:Médias, CC:Finas, GG:Finas"],
    ["rs1805008", "Sensibilidade Solar", "Aparência", "TT:Alta, AA:Alta, CT:Média, CC:Baixa, GG:Baixa"],
    ["rs10156191", "Pele Seca", "Aparência", "TT:Alta, AA:Alta, CT:Média, CC:Baixa, GG:Baixa"],
    ["rs4844610", "Pele Oleosa", "Aparência", "GG:Alta, CC:Alta, AG:Média, AA:Baixa, TT:Baixa"],
    ["rs2497938", "Tendência a Varizes", "Aparência", "AA:Alta, TT:Alta, AG:Média, GG:Baixa, CC:Baixa"],
    ["rs10458597", "Formato do Rosto", "Aparência", "CC:Arredondado, GG:Arredondado, CT:Oval, TT:Alongado, AA:Alongado"],

    # SAÚDE E PERFORMANCE (20 itens)
    ["rs1229984", "Mal-estar com Álcool", "Saúde", "TT:Alto, AA:Alto, CT:Médio, CC:Normal, GG:Normal"],
    ["rs1801260", "Relógio Biológico", "Sono", "AA:Manhã, TT:Manhã, AG:Misto, GG:Noite, CC:Noite"],
    ["rs5051", "Pressão e Sal", "Saúde", "AA:Sensível, TT:Sensível, AG:Médio, GG:Normal, CC:Normal"],
    ["rs4880", "Limpeza Celular", "Saúde", "TT:Eficiente, AA:Eficiente, CT:Normal, CC:Lenta, GG:Lenta"],
    ["rs1799983", "Saúde das Artérias", "Saúde", "GG:Excelente, CC:Excelente, GT:Bom, TT:Normal, AA:Normal"],
    ["rs2802288", "Longevidade", "Saúde", "GG:Alta, CC:Alta, GT:Média, TT:Normal, AA:Normal"],
    ["rs1800795", "Inflamação Pós-Treino", "Esporte", "GG:Baixa, CC:Baixa, CG:Média, CC:Alta, GG:Alta"],
    ["rs8192678", "Energia das Mitocôndrias", "Esporte", "AA:Alta, TT:Alta, AG:Média, GG:Normal, CC:Normal"],
    ["rs143383", "Articulações", "Esporte", "GG:Fortes, CC:Fortes, AG:Médias, AA:Frágeis, TT:Frágeis"],
    ["rs4646994", "Capacidade Cardiovascular", "Esporte", "CC:Alta, GG:Alta, CT:Média, TT:Normal, AA:Normal"],
    ["rs1805035", "Massa Muscular", "Esporte", "GG:Rápido, CC:Rápido, AG:Médio, AA:Normal, TT:Normal"],
    ["rs11244484", "Resistência à Fadiga", "Esporte", "AA:Alta, TT:Alta, AG:Média, GG:Normal, CC:Normal"],
    ["rs8111989", "Recuperação Muscular", "Esporte", "GG:Rápida, CC:Rápida, AG:Média, AA:Lenta, TT:Lenta"],
    ["rs1800012", "Risco de Lesões", "Esporte", "CC:Baixo, GG:Baixo, CT:Médio, TT:Alto, AA:Alto"],
    ["rs1042713", "Queima de Gordura no Treino", "Esporte", "GG:Eficiente, CC:Eficiente, AG:Média, AA:Baixa, TT:Baixa"],
    ["rs1205", "Inflamação Natural", "Saúde", "GG:Baixo, CC:Baixo, AG:Médio, AA:Alto, TT:Alto"],
    ["rs17602729", "Energia Muscular (ATP)", "Esporte", "GG:Rápida, CC:Rápida, AG:Média, AA:Lenta, TT:Lenta"],
    ["rs2273068", "Metabolismo em Jejum", "Saúde", "AA:Eficiente, TT:Eficiente, AG:Normal, GG:Lento, CC:Lento"],
    ["rs2736100", "Envelhecimento Celular", "Saúde", "AA:Lento, TT:Lento, AG:Médio, GG:Rápido, CC:Rápido"],
    ["rs1800562", "Sensibilidade ao Ferro", "Saúde", "GG:Normal, CC:Normal, AG:Sensível, AA:Alta, TT:Alta"]
]

df_map = pd.DataFrame(caracteristicas_100, columns=["RSID", "Característica", "Categoria", "Tradução"])
df_map.to_csv("mapeamento_completo_100.csv", index=False)
print("Base de dados com 100 itens criada!")